### ISSUE TITLE
記事の内容が似ているものについて

### ISSUE THREAD

**Issue by InkoHX** [tubuanha/zenn-blog#5]
こんにちは、Discord.js Japan User GroupというコミュニティでモデレーターをしているInkoHXといいます。

単刀直入に言うと、[discord.jsでYouTube動画を流す](https://zenn.dev/tubuan/articles/discordjs-youtube)という記事が当コミュニティが管理するScrapboxのページ「[ytdl-core を使用して YouTube の音源を配信するサンプル](https://scrapbox.io/discordjs-japan/ytdl-core_を使用して_YouTube_の音源を配信するサンプル)」のコード部分（変数名が多少違う、セミコロンが付いているなどの違いはあります）が、非常に似ていて引用したという記述もない、そして何より**収益を得ている可能性**があるためissuesを作成した次第でございます。このコードは @tubuanha 様が書かれたものなのか教えてくださるとありがたいです。

## 該当するコード

- [discord.jsでYouTube動画を流す - コード全文](https://zenn.dev/tubuan/articles/discordjs-youtube#%E3%82%B3%E3%83%BC%E3%83%89%E5%85%A8%E6%96%87)

```js
const ytdl = require('ytdl-core')

client.on('message', async message => {
  if (message.content.startsWith('!play') && message.guild) {
    const playurl = message.content.split(' ')[1];
    if (!ytdl.validateURL(playurl)) return message.reply('YouTubeにその動画が存在しません。URLをご確認ください。');
    const userch = message.member.voice.channel;
    if (!userch) return message.reply('コマンドを実行する前にボイスチャンネルに参加してください。');
    const connection = await channel.join();
    const stream = ytdl(ytdl.getURLVideoID(playurl), { filter: 'audioonly' });
    const dispatcher = connection.play(stream);
    dispatcher.once('finish', () => { channel.leave() });
  }
});
```

## Scrapbox側のコード

```js
const ytdl = require('ytdl-core')
 
 client.on('message', async message => {
   // メッセージが "!yt" からはじまっていてサーバー内だったら実行する
   if (message.content.startsWith('!yt') && message.guild) {
     // メッセージから動画URLだけを取り出す
     const url = message.content.split(' ')[1]
     // まず動画が見つからなければ処理を止める
     if (!ytdl.validateURL(url)) return message.reply('動画が存在しません！')
     // コマンドを実行したメンバーがいるボイスチャンネルを取得
     const channel = message.member.voice.channel
     // コマンドを実行したメンバーがボイスチャンネルに入ってなければ処理を止める
     if (!channel) return message.reply('先にボイスチャンネルに参加してください！')
     // チャンネルに参加
     const connection = await channel.join()
     // 動画の音源を取得
     const stream = ytdl(ytdl.getURLVideoID(url), { filter: 'audioonly' })
     // 再生
     const dispatcher = connection.play(stream)
     
     // 再生が終了したら抜ける
     dispatcher.once('finish', () => {
       channel.leave()
     })
   }
 })
```

**Comment by tubuanha** [comment]
こんにちは。
この記事はとある方に「YouTubeの動画の音声を流すにはどうしたらいいんですか？調べてもでてこなくせ」と聞かれて書いた記事で、
discord.js user groupさんが管理されている記事とは全く関係ないです。というかその記事今知りました。

この記事はリファレンスとどこかの海外記事を見て書いた記憶があります。

削除した方がいいのであれば削除します。(ちなみに収益は得られてないです)

**Comment by InkoHX** [comment]
返信ありがとうございます。気になる点に返信させていただきます。

> この記事はリファレンスとどこかの海外記事を見て書いた記憶があります。

リファレンスを参照されているのは、記事から読み取れますので分かります。
ただ海外記事というのは具体的にどちらを参考にされたのでしょうか？お手数ですが、ソースのリンクを送ってほしいです。

> 削除した方がいいのであれば削除します。

こちら側が海外記事のソース元を確認できてから判断しましょう。

> ちなみに収益は得られてないです

そうなのですね。Zennには金銭的なやり取りを可能にする機能があるので、収益を得られているのではないかと考えておりました。
申し訳ございません。

**Comment by tubuanha** [comment]
海外記事の件ですが、検索してみたんですが参考にしたものがヒットせず、履歴にも残していない(自動削除の設定にしているので)のでリンクが出せません。すみません。

discord.js japan communityさんの記事からの転載でないという証明ができなかったので、記事は削除することにします。
お手間を取らせてしまい、申し訳ございませんでした。

**Comment by InkoHX** [comment]
こちらこそお手数おかけしました。ありがとうございました。
